server:
  port: 4000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

---
spring:
  cloud:
    gateway:
      routes:
#      - id: practice
#        uri: http://www.baidu.com
#        predicates:
#        - After=datetime
#        - Before=datetime
#        - Between=datetime,datetime
#        - Cookie=cookieName,cookieValue regular expression
#        - Header=headerName,headerValue regular expression
#        - Host=**.somehost.org
#        - Method=http method
#        - Query=requestParam(required),regular expression(optional)
#        - RemoteAddr=192.168.1.10/16 
#        - Path=
#        filters:
#        - AddRequestParameter=key,value
#        - AddResponseHeader=key,value
#        - Hystrix=myCommandName
#        - PrefixPath=/mypath  #uri添加前缀/mypath
#        - PreserveHostHeader
#        - RequestRateLimiter
#        - RedirectTo=302, http://acme.org
#        - RemoveRequestHeader=requestHeaderName
#        - RemoveResponseHeader=responseHeaderName
#        - RewritePath=/foo/(?<segment>.*), /$\{segment}
#        - SaveSession
#        - SetPath=/{segment}
#        - SetResponseHeader=responseHeaderName, new value
#        - SetStatus=401 (It must be a valid Spring HttpStatus)
#        - StripPrefix=2
#        - Retry
      - id: test-ribbon
        uri: lb://SPRINGBOOT-SERVICE
        predicates:
        - Path=/springboot-service/**
        filters:
        - StripPrefix=1
      - id: test-http
        uri: http://www.baidu.com
        predicates:
        - Path=/forward/**
        filters:
        - StripPrefix=1
          
          
        
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug