server:
  port: 4000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
                               #服务名忽略大小写
          lower-case-service-id: true

---
spring:
#  zipkin:
#    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      default-filters:
      - CustomLocal=true  #应用于每个路由的过滤器列表，但是只试用于下面的filters，java配置无效
                  #限流放在default-filters报错找不到   No Configuration found for route test-ribbon
#      - name: RequestRateLimiter
      routes:
#      - id: practice
#        uri: http://www.baidu.com
#        predicates:
#        - After=datetime
#        - Before=datetime
#        - Between=datetime,datetime
#        - Cookie=cookieName,cookieValue regular expression
#        - Header=headerName,headerValue regular expression
#        - Host=**.somehost.org
#        - Method=http method
#        - Query=requestParam(required),regular expression(optional)
#        - RemoteAddr=192.168.1.10/16 
#        - Path=
#        filters:
#        - AddRequestParameter=key,value
#        - AddResponseHeader=key,value
#        - Hystrix=myCommandName
#        - PrefixPath=/mypath  #uri添加前缀/mypath
#        - PreserveHostHeader
#        - RequestRateLimiter
#        - RedirectTo=302, http://acme.org
#        - RemoveRequestHeader=requestHeaderName
#        - RemoveResponseHeader=responseHeaderName
#        - RewritePath=/foo/(?<segment>.*), /$\{segment}
#        - SaveSession
#        - SetPath=/{segment}
#        - SetResponseHeader=responseHeaderName, new value
#        - SetStatus=401 (It must be a valid Spring HttpStatus)
#        - StripPrefix=2
#        - Retry
      - id: test-lower-case-service-id
        uri: lb://springboot-service
        predicates:
        - Path=/lower-case/**
        filters:
        - StripPrefix=1
        - name: Hystrix
          args:
            name: authHystrixCommand
            fallbackUri: forward:localhost:1111/hystrixTimeout
      - id: test-ribbon
        uri: lb://SPRINGBOOT-SERVICE
        predicates:
        - Path=/springboot/**
        filters:
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@userKeyResolver}"
                                    #是您希望允许用户每秒执行多少请求，而不会丢弃任何请求。这是令牌桶填充的速率。
            redis-rate-limiter.replenishRate: 1
                                    #是用户在一秒钟内允许执行的最大请求数。这是令牌桶可以容纳的令牌数。将此值设置为零将阻止所有请求。
            redis-rate-limiter.burstCapacity: 2
        - StripPrefix=1
        - name: Hystrix
          args:
            name: authHystrixCommand
            fallbackUri: forward:/hystrixTimeout
      - id: test-http
        uri: http://www.baidu.com
        predicates:
        - Path=/forward/**
        filters:
        - StripPrefix=1
      - id: test-hystrix
        uri: http://www.baidu.com
        predicates:
        - Path=/testHystrix/**
        filters:
        - StripPrefix=1
        - name: Hystrix
          args:
            name: testHystrix
            fallbackUri: forward:/fallback
          
hystrix:
  command:
    hystrixCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    authHystrixCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000    
    
            
#ribbon:
#  ReadTimeout: 2000
#  ConnectTimeout: 2000

        
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka/
logging:
#  config: "classpath:logback-spring.xml" 
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.cloud.gateway: debug